### ISSUE TITLE
onSelectDate method?

### ISSUE THREAD

**Issue by LeoJHarris** [dpreussler/clean-simple-calendar#3]
Hi, is there a select date method available on the widget? Some way to get the date selected by the user.

**Comment by dpreussler** [comment]
Hi Leo,

sorry for the late response.

There are multiple ways to achieve this. Easiest is probably extend the CalendarAdapter and override the
_  public void select(Day selectedDay)_

to let the widget use your adapter override 
_   public CalendarAdapter createAdapterFor(LayoutInflater inflater, VisibleMonths months)_
in the CalendarBuilder

**Comment by disav1** [comment]
`
    ArrayList<SelectDateListener> listeners;

    public void setOnSelectDateListener (SelectDateListener listener)
    {
        this.listeners.add(listener);
    }

    public interface SelectDateListener
    {
        void OnSelectDate(Date date);
    }
        mCalendarWidget.setOnSelectDateListener(new CalenderWidget.SelectDateListener() {
            @Override
            public void OnSelectDate(Date date) {
                Utils.showMessage(getContext(), date.toString());
            }
        });

`
